const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setMsg(text,error=false){const msg=$('msg');if(msg){msg.textContent=text;msg.className=error?'msg error-msg':'msg'}}
async function load(){const g=$('gallery');if(!g)return;const {data,error}=await db.from('photos').select('*').order('created_at',{ascending:false});if(error){g.innerHTML='<div class="empty">Could not load memories.</div>';return}if(!data.length){g.innerHTML='<div class="empty">No memories yet. Be the first to upload one.</div>';return}g.innerHTML=data.map(p=>{const url=p.image_url||db.storage.from('gallery').getPublicUrl(p.image_path).data.publicUrl;return `<article class="card"><img src="${url}" alt="${escapeHtml(p.title||'Memory')}" loading="lazy"><div class="caption">${escapeHtml(p.title||'Untitled memory')}</div></article>`}).join('')}
$('file')?.addEventListener('change',()=>{const f=$('file').files?.[0],preview=$('preview');if(!f||!preview)return;preview.src=URL.createObjectURL(f);preview.style.display='block'});
$('upload')?.addEventListener('click',async()=>{const f=$('file').files?.[0],title=$('title').value.trim();if(!f)return setMsg('Choose an image first.',true);if(!f.type.startsWith('image/'))return setMsg('Only image files are allowed.',true);if(f.size>10*1024*1024)return setMsg('Image must be 10MB or smaller.',true);const safeName=f.name.replace(/[^a-zA-Z0-9._-]/g,'')||'image';const path=`${crypto.randomUUID()}-${safeName}`;const button=$('upload');button.disabled=true;setMsg('Uploading…');const {error:uploadError}=await db.storage.from('gallery').upload(path,f,{contentType:f.type,upsert:false});if(uploadError){button.disabled=false;return setMsg(uploadError.message,true)}const publicUrl=db.storage.from('gallery').getPublicUrl(path).data.publicUrl;const {error:insertError}=await db.from('photos').insert({title,image_path:path,image_url:publicUrl});if(insertError){await db.storage.from('gallery').remove([path]);button.disabled=false;return setMsg(insertError.message,true)}$('title').value='';$('file').value='';$('preview').style.display='none';button.disabled=false;setMsg('Uploaded! 🎉');await load()});
load();
