const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const CATEGORIES=['Travel','Art','Cityscape','Nature','Inspiration'];
const OWNER_KEY='gallarify_owner_tokens';
const $=id=>document.getElementById(id);let selectedCategory='',activeCategory='',currentView='explore';
const favorites=new Set(JSON.parse(localStorage.getItem('gallarify_favorites')||'[]'));const owners=JSON.parse(localStorage.getItem(OWNER_KEY)||'{}');
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setMsg(text,error=false){const msg=$('msg');if(msg){msg.textContent=text;msg.className=error?'msg error-msg':'msg'}}
function saveFavorites(){localStorage.setItem('gallarify_favorites',JSON.stringify([...favorites]));if($('favoriteCount'))$('favoriteCount').textContent=favorites.size}
function saveOwners(){localStorage.setItem(OWNER_KEY,JSON.stringify(owners))}
function newOwnerToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
function selectCategory(cat){selectedCategory=cat;document.querySelectorAll('#uploadCategories .category-button').forEach(b=>b.classList.toggle('selected',b.dataset.category===cat));updateUploadState()}
function updateUploadState(){$('upload').disabled=!Boolean(selectedCategory&&$('file')?.files?.[0])}
function buildCategoryLists(){const side=CATEGORIES.map(c=>`<button class="category-filter" data-category="${c}">${c}</button>`).join('');$('categoryList').innerHTML=side;$('mobileTags').innerHTML=`<button class="category-filter active" data-category="">All</button>${side}`;document.querySelectorAll('.category-filter').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category||'';currentView='explore';document.querySelectorAll('.category-filter').forEach(x=>x.classList.toggle('active',(x.dataset.category||'')===activeCategory));syncViewButtons();load()}))}
function syncViewButtons(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));$('feedTitle').textContent=currentView==='favorites'?'Your favorites':activeCategory||'Latest photos'}
async function load(){const g=$('gallery');if(!g)return;g.innerHTML='<div class="loading">Loading the wall…</div>';const {data,error}=await db.from('photos').select('id,title,image_path,image_url,category,created_at').order('created_at',{ascending:false});if(error){g.innerHTML='<div class="empty">Could not load the gallery.</div>';return}const search=$('search').value.trim().toLowerCase();let rows=(data||[]).filter(r=>!search||String(r.title||'').toLowerCase().includes(search)||String(r.category||'').toLowerCase().includes(search));if(activeCategory)rows=rows.filter(r=>(r.category||'Inspiration')===activeCategory);if(currentView==='favorites')rows=rows.filter(r=>favorites.has(r.id));$('resultNote').textContent=`${rows.length} ${rows.length===1?'photo':'photos'} · public gallery · anonymous uploads`;if(!rows.length){g.innerHTML='<div class="empty">Nothing here yet.</div>';return}g.innerHTML=rows.map(cardHtml).join('');bindCardActions()}
function cardHtml(p){const url=p.image_url||db.storage.from('gallery').getPublicUrl(p.image_path).data.publicUrl;const fav=favorites.has(p.id);const mine=Boolean(owners[p.id]);return `<article class="card"><div class="card-media"><img class="gallery-image" src="${escapeHtml(url)}" alt="${escapeHtml(p.title||'Memory')}" loading="lazy" data-full-image="${escapeHtml(url)}"><div class="card-overlay"><span class="creator">@anonymous</span><div class="card-actions"><button class="icon-button favorite ${fav?'active':''}" data-id="${p.id}" aria-label="${fav?'Remove from favorites':'Add to favorites'}" title="${fav?'Remove from favorites':'Add to favorites'}">${fav?'♥':'♡'}</button><button class="icon-button download" data-url="${escapeHtml(url)}" data-name="gallerify-${p.id}" aria-label="Download image" title="Download image">↓</button></div></div></div><div class="card-info"><span class="category-tag">${escapeHtml(p.category||'Inspiration')}</span><div class="caption">${escapeHtml(p.title||'Untitled memory')}</div>${mine?'<button class="delete-button" data-id="'+p.id+'" aria-label="Delete your image">Delete image</button>':''}</div></article>`}
function bindCardActions(){document.querySelectorAll('.favorite').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.id;if(favorites.has(id))favorites.delete(id);else favorites.add(id);saveFavorites();load()}));document.querySelectorAll('.download').forEach(b=>b.addEventListener('click',()=>downloadImage(b.dataset.url,b.dataset.name)));document.querySelectorAll('.delete-button').forEach(b=>b.addEventListener('click',()=>deleteOwnPhoto(b.dataset.id)));document.querySelectorAll('.gallery-image').forEach(img=>img.addEventListener('click',()=>openLightbox(img.dataset.fullImage,img.alt)))}
function openLightbox(url,alt='Image'){let box=document.getElementById('lightbox');if(!box){box=document.createElement('div');box.id='lightbox';box.className='lightbox';box.innerHTML='<button class="lightbox-close" aria-label="Close image">×</button><img class="lightbox-image" alt="">';document.body.appendChild(box);box.addEventListener('click',e=>{if(e.target===box||e.target.classList.contains('lightbox-close'))box.classList.remove('open')})}box.querySelector('.lightbox-image').src=url;box.querySelector('.lightbox-image').alt=alt;box.classList.add('open')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('lightbox')?.classList.remove('open')});
async function downloadImage(url,name){try{const res=await fetch(url);if(!res.ok)throw new Error();const blob=await res.blob();const objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=`${name}.jpg`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000)}catch{window.open(url,'_blank','noopener,noreferrer')}}
async function deleteOwnPhoto(id){const token=owners[id];if(!token)return setMsg('Only the original uploader can delete this image.',true);if(!confirm('Delete your image permanently?'))return;const {data,error}=await db.rpc('delete_photo',{p_id:id,p_owner_token:token});if(error||!data){setMsg(error?.message||'Delete failed.',true);return}delete owners[id];saveOwners();favorites.delete(id);saveFavorites();setMsg('Your image was deleted.');await load()}
$('file').addEventListener('change',()=>{const f=$('file').files?.[0],preview=$('preview');updateUploadState();if(!f)return;if(!f.type.startsWith('image/')){setMsg('Only image files are allowed.',true);return}if(f.size>10*1024*1024){setMsg('Image must be 10MB or smaller.',true);return}preview.src=URL.createObjectURL(f);preview.style.display='block';setMsg('')});
document.querySelectorAll('#uploadCategories .category-button').forEach(b=>b.addEventListener('click',()=>selectCategory(b.dataset.category)));
$('upload').addEventListener('click',async()=>{const f=$('file').files?.[0],title=$('title').value.trim();if(!selectedCategory)return setMsg('Choose a category first.',true);if(!f)return setMsg('Choose an image first.',true);const safeName=f.name.replace(/[^a-zA-Z0-9._-]/g,'')||'image',path=`${crypto.randomUUID()}-${safeName}`,button=$('upload');button.disabled=true;setMsg('Publishing anonymously…');const {error:uploadError}=await db.storage.from('gallery').upload(path,f,{contentType:f.type,upsert:false});if(uploadError){setMsg(uploadError.message,true);updateUploadState();return}const publicUrl=db.storage.from('gallery').getPublicUrl(path).data.publicUrl;const token=newOwnerToken();const {data:created,error:insertError}=await db.rpc('create_photo',{p_title:title,p_image_path:path,p_image_url:publicUrl,p_category:selectedCategory,p_owner_token:token});if(insertError||!created){await db.storage.from('gallery').remove([path]);setMsg(insertError?.message||'Could not publish image.',true);updateUploadState();return}owners[created.id]=token;saveOwners();$('title').value='';$('file').value='';$('preview').style.display='none';selectedCategory='';document.querySelectorAll('#uploadCategories .category-button').forEach(b=>b.classList.remove('selected'));setMsg('Published anonymously.');await load();updateUploadState()});
$('search').addEventListener('input',load);$('jumpUpload').addEventListener('click',()=>document.querySelector('#upload').scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;activeCategory='';document.querySelectorAll('.category-filter').forEach(x=>x.classList.toggle('active',(x.dataset.category||'')===''));syncViewButtons();load()}));buildCategoryLists();saveFavorites();syncViewButtons();load();